add sponsorship package
nodeschool/vancouver pull request #68
Opened 2018-03-12 07:26 UTC by chowdhurian

Some changes are needed before merge:
* We need a designated contact.

2018-03-12 08:41 UTC, codeekage requested changes

2018-03-12 08:41 UTC, codeekage commented on docs/sponsorship-package.md
> +NodeSchoolYVR offers one benefits tier to any and all cash sponsors. Sponsorship funds with be used for, but is not limited to, food, drinks, and operational costs.
typo with -> will

2018-03-12 16:38 UTC, Qard commented
Looks pretty good. One thing to consider is how Gastown Gang stuff will impact this in the future. We should, at the least, communicate the existence of Gastown Gang when speaking to potential sponsors and have some plan on how to migrate their sponsorship in the future.

2018-03-12 20:00 UTC, chowdhurian commented on docs/sponsorship-package.md
> +NodeSchoolYVR offers one benefits tier to any and all cash sponsors. Sponsorship funds with be used for, but is not limited to, food, drinks, and operational costs.
Thanks for reviewing!

2018-03-12 20:29 UTC, chowdhurian commented
We can def communicate the existence of Gastown Gang when speaking to sponsors.

I can push up some edits to include a mention of Gastown Gang. But without public information about Gastown Gang, I'm concerned that would be confusing. We could link to the repo for now, or wait until a page is up.

I'm open to any input.

2018-03-18 21:03 UTC, Qard approved these changes

2018-05-01 01:21 UTC, merged